# Generated by Django 5.0.6 on 2024-05-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YouTubeVideo',
        ),
    ]
