export interface IContestant {
    queue: number;
    fio: string;
    organization: string;
    participation: string;
    direction: string;
    theme_of_perfomance: string;
}

export const contestantData: IContestant[] = [
    {
        queue: 0,
        fio: "Бабиченко Никита Александрович",
        organization: "ЮФУ",
        participation: "Очное",
        direction: "Информационные технологии",
        theme_of_perfomance: "Базы данных в окружающем мире",
    },
    {
        queue: 1,
        fio: "Поярков Даниил Сергеевич",
        organization: "ЮФУ",
        participation: "Очное",
        direction: "Инновационные технологии",
        theme_of_perfomance: "Как создать все что угодно из ничего",
    },
    {
        queue: 2,
        fio: "Шац Александра Михайловна",
        organization: "ДГТУ",
        participation: "Очное",
        direction: "Лингвистика",
        theme_of_perfomance: "Языки ближнего востока",
    },
    {
        queue: 3,
        fio: "Иванов Иван Иванович",
        organization: "МГУ",
        participation: "Заочное",
        direction: "Физика",
        theme_of_perfomance: "Квантовые вычисления",
    },
    {
        queue: 4,
        fio: "Петрова Анна Владимировна",
        organization: "СПбГУ",
        participation: "Очное",
        direction: "Биология",
        theme_of_perfomance: "Генетика человека",
    },
    {
        queue: 5,
        fio: "Сидоров Алексей Петрович",
        organization: "НГУ",
        participation: "Очное",
        direction: "Химия",
        theme_of_perfomance: "Новые полимерные материалы",
    },
    {
        queue: 6,
        fio: "Кузнецова Елена Дмитриевна",
        organization: "КФУ",
        participation: "Заочное",
        direction: "Психология",
        theme_of_perfomance: "Когнитивные искажения",
    },
    {
        queue: 7,
        fio: "Смирнов Артем Олегович",
        organization: "ТГУ",
        participation: "Очное",
        direction: "Математика",
        theme_of_perfomance: "Теория графов",
    },
    {
        queue: 8,
        fio: "Васильева Мария Сергеевна",
        organization: "УрФУ",
        participation: "Очное",
        direction: "Экономика",
        theme_of_perfomance: "Криптовалюты и блокчейн",
    },
    {
        queue: 9,
        fio: "Попов Денис Андреевич",
        organization: "БГУ",
        participation: "Заочное",
        direction: "История",
        theme_of_perfomance: "Средневековые города Европы",
    },
    {
        queue: 10,
        fio: "Федорова Ольга Игоревна",
        organization: "ДВФУ",
        participation: "Очное",
        direction: "Экология",
        theme_of_perfomance: "Изменение климата",
    },
    {
        queue: 11,
        fio: "Лебедев Михаил Викторович",
        organization: "СФУ",
        participation: "Очное",
        direction: "Робототехника",
        theme_of_perfomance: "Искусственный интеллект в робототехнике",
    },
    {
        queue: 12,
        fio: "Новикова Анастасия Павловна",
        organization: "РУДН",
        participation: "Заочное",
        direction: "Медицина",
        theme_of_perfomance: "Нейродегенеративные заболевания",
    },
    {
        queue: 13,
        fio: "Козлов Андрей Николаевич",
        organization: "МФТИ",
        participation: "Очное",
        direction: "Астрофизика",
        theme_of_perfomance: "Черные дыры",
    },
    {
        queue: 14,
        fio: "Орлова Виктория Александровна",
        organization: "ВШЭ",
        participation: "Очное",
        direction: "Социология",
        theme_of_perfomance: "Социальные сети и общество",
    },
    {
        queue: 15,
        fio: "Морозов Дмитрий Евгеньевич",
        organization: "МИФИ",
        participation: "Очное",
        direction: "Ядерная физика",
        theme_of_perfomance: "Ядерные реакторы нового поколения",
    },
    {
        queue: 16,
        fio: "Антонова Екатерина Валерьевна",
        organization: "МГИМО",
        participation: "Заочное",
        direction: "Международные отношения",
        theme_of_perfomance: "Глобализация и культура",
    },
    {
        queue: 17,
        fio: "Тарасов Павел Алексеевич",
        organization: "СГУ",
        participation: "Очное",
        direction: "Философия",
        theme_of_perfomance: "Этика искусственного интеллекта",
    },
    {
        queue: 18,
        fio: "Белова Юлия Олеговна",
        organization: "РЭУ им. Плеханова",
        participation: "Очное",
        direction: "Маркетинг",
        theme_of_perfomance: "Нейромаркетинг",
    },
    {
        queue: 19,
        fio: "Григорьев Игорь Дмитриевич",
        organization: "МАИ",
        participation: "Очное",
        direction: "Авиастроение",
        theme_of_perfomance: "Беспилотные летательные аппараты",
    },
    {
        queue: 20,
        fio: "Соколова Алина Романовна",
        organization: "РАНХиГС",
        participation: "Заочное",
        direction: "Государственное управление",
        theme_of_perfomance: "Цифровизация государственных услуг",
    },
    {
        queue: 21,
        fio: "Павлов Артем Витальевич",
        organization: "МГТУ им. Баумана",
        participation: "Очное",
        direction: "Машиностроение",
        theme_of_perfomance: "Автомобили будущего",
    },
    {
        queue: 22,
        fio: "Киселева Дарья Андреевна",
        organization: "РГГУ",
        participation: "Очное",
        direction: "Искусствоведение",
        theme_of_perfomance: "Современное искусство и технологии",
    },
];